### ISSUE TITLE
Updated new fayde version errors

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#156]
Updated new fayde version its giving me below errors

```cmd
Running "typescript:build" (typescript) task
>> app/lib/fayde/dist/fayde.d.ts(2902,34): error TS1005: ',' expected.
>> app/lib/fayde/dist/fayde.d.ts(2902,40): error TS1005: ',' expected.
>> app/lib/fayde/dist/fayde.d.ts(2946,22): error TS1005: ';' expected.
>> app/lib/fayde/dist/fayde.d.ts(2946,24): error TS1036: Statements are not allowed in ambient contexts.
>> app/lib/fayde/dist/fayde.d.ts(2946,24): error TS1131: Property or signature expected.
>> app/lib/fayde/dist/fayde.d.ts(2947,22): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2948,23): error TS1109: Expression expected.
Process terminated with code 3.
>> app/lib/fayde/dist/fayde.d.ts(2949,25): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2950,31): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2951,19): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2952,28): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2953,26): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2954,21): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2955,14): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2956,33): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2957,24): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2958,16): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2959,29): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2960,31): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2961,31): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2962,37): error TS1109: Expression expected.
>> app/lib/fayde/dist/fayde.d.ts(2964,1): error TS1128: Declaration or statement expected.
Warning: Task "typescript:build" failed. Use --force to continue.
Aborted due to warnings.
```

**Comment by Sally-Xu** [comment]
I just updated with the latest fayde, my build is fine.  But I have seen build errors often when update to new version, I think most of them are due the dependencies are still in older version.  Not sure if it is a problem of bower update, or a cache problem, or because bower.json not updated in the Fayde's project to require the latest dependencies.  

For example, the latest minerva is v. 0.4.23, the latest perfex is v. 0.1.14, but here is what listed in fayde's bower.json:
    "minerva": "~0.4.22",
    "perfex": "~0.1.0".

**Comment by BSick7** [comment]
Try running `grunt lib:reset` if this ever happens.

**Comment by Sally-Xu** [comment]
Yes, that's what I usually do. But sometimes, that doesn't work either. 

I have all the Fayde projects cloned, and I'm mainly working on the Fayde.Controls project most of time. When you have a new build on fayde/nullstone/minerva, I usually just update my bower.json under Fayde.Controls project to point to the new version. After bower update, sometime I can see build error,  And I can tell the build error was due to dependency mismatch.  This can be very frustrating, has wasted a lot of time in development.

**Comment by BSick7** [comment]
Fayde does not need to list the latest minerva or nullstone versions.  The tilde at the beginning allows bower to resolve any "compatible" version.  In other words, when installing dependencies ~0.4.22 will install 0.4.23 because it is the latest compatible version.  It will not install 0.5+.

**Comment by deepaksm1** [comment]
I am creating new fayde project using yo fayde. ```grunt lib:reset``` task is not there.

**Comment by deepaksm1** [comment]
My issue is solved.
