### ISSUE TITLE
new to fayde, few questions

### ISSUE THREAD

**Issue by mikefills** [wsick/Fayde#234]
1. What web-browsers and versions are supported?
2. Examples of apps in production using fayde.io?
3. Is there any room for improving the load time?

Thanks!

**Comment by BSick7** [comment]
1. IE9+ is supported; however, I would rather not support browser that Microsoft no longer supports.
Since Firefox and Chrome auto-update, the last 3 versions are supported.  Safari isn't 100% verified, but I am very confident that any bugs that emerge are minor.

2. @Ronmenator just recently rebuilt their Silverlight application; however, I don't think it's public. @asthomas has also been prototyping a port from Silverlight as well.  I originally built fayde.io library for @Ronmenator team.  Hopefully he can chime in.

3. I am currently working on a lot of performance improvements out of band that may take some time to work their way back into Fayde.

**Comment by mikefills** [comment]
I'm on Windows 10, I got this error when running 'yo fayde':

![snip_20160201193047](https://cloud.githubusercontent.com/assets/15019084/12725242/5a73ab66-c91a-11e5-93f0-45a7964b3cf1.jpg)

Note that I installed gulp, yeoman, bower without -g flag
In order to make it work I ran this in node command line:
 'SET PATH=%PATH%;D:\Projects\MyProject\node_modules\.bin'

**Comment by mikefills** [comment]
meh, I also ran 'npm install unify' and I had to create 2 files in 'npm_modules/bin' so that 'unify' is available.

I ran 'gulp build' and 'gulp serve' when I navigate to the 'http://localhost:8000/' it shows blank page and  I see errors in console.

> text.js:308 GET http://localhost:8000/fayde.json 404 (Not Found)

I guess I am missing few things

**Comment by mikefills** [comment]
Can someone post info how to run demos from Fayde-Demos?
Running gulp command in the Todo folder gives me this:

```
app\Models\TodoItem.ts(1,15): error TS2304: Cannot find name 'Fayde'.
app\Models\TodoItem.ts(1,15): error TS2503: Cannot find namespace 'Fayde'.
app\Models\TodoItem.ts(7,24): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\FilterObject.ts(2,15): error TS2304: Cannot find name 'Fayde'.
app\ViewModels\FilterObject.ts(2,15): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\FilterObject.ts(3,29): error TS2304: Cannot find name 'Fayde'.
app\ViewModels\FilterObject.ts(3,29): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\FilterObject.ts(4,35): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\MainViewModel.ts(3,15): error TS2304: Cannot find name 'Fayde'.
app\ViewModels\MainViewModel.ts(3,15): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\MainViewModel.ts(4,35): error TS2304: Cannot find name 'Fayde'.
app\ViewModels\MainViewModel.ts(4,35): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\MainViewModel.ts(18,16): error TS2304: Cannot find name 'ex'.
app\ViewModels\MainViewModel.ts(21,53): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\MainViewModel.ts(22,14): error TS2339: Property 'OnPropertyChanged' does not exist on type 'MainViewModel'.
app\ViewModels\MainViewModel.ts(23,14): error TS2339: Property 'OnPropertyChanged' does not exist on type 'MainViewModel'.
app\ViewModels\MainViewModel.ts(27,16): error TS2304: Cannot find name 'ex'.
app\ViewModels\MainViewModel.ts(31,9): error TS2304: Cannot find name 'ex'.
app\ViewModels\MainViewModel.ts(34,17): error TS2503: Cannot find namespace 'Fayde'.
app\ViewModels\MainViewModel.ts(35,28): error TS2304: Cannot find name 'Fayde'.
app\ViewModels\MainViewModel.ts(43,14): error TS2339: Property 'OnPropertyChanged' does not exist on type 'MainViewModel'.
app\ViewModels\MainViewModel.ts(44,14): error TS2339: Property 'OnPropertyChanged' does not exist on type 'MainViewModel'.
```

**Comment by BSick7** [comment]
As mentioned in gitter, make sure you issue commands in an admin console.
Also, unify should be installed globally -> `npm install -g unify`

**Comment by mikefills** [comment]
wondering if there's any difference between 'unify' and 'generator-fayde'

**Comment by BSick7** [comment]
The github readme needs to either point to fayde.io for "Getting Started" or updated.

**Comment by Ronmenator** [comment]
Hi @mikefills,

We are in the final stages of releasing our vendor management system in Fayde. The technology is very stable and is the only library to work on all the latest browsers on all the platforms and operate, look and feel the same without having to code for any eventuality that HTML would bring due to browser compatibility issues.

**Comment by mikefills** [comment]
@Ronmenator I wouldn't call it "very stable" and work "on all latest browsers and platforms". 
From little testing I saw there are some issues related to basic usage but also related to performance.
Not my intention to bash it or anything, I'm just giving my opinion and feedback.
