### ISSUE TITLE
Unsharp text and graphics 

### ISSUE THREAD

**Issue by Ziriax** [wsick/Fayde#87]
The TODO sample gives blurry text on my machine. 

Reason: I have a high DPI monitor, and my `window.devicePixelRatio` is not `1.0`, but `1.25`

This will also happen on almost all tablets

[How to fix this](http://www.html5rocks.com/en/tutorials/canvas/hidpi)

**Comment by BSick7** [comment]
Could you come up with a contextual solution?

**Comment by asthomas** [comment]
I have more information on this:

1) dpiRatio is dynamic.  Every time RenderContext.resize is called, the dpiRatio could change.  You need to make dpiRatio writable, and calculate it within the resize method.  Specifically, window.devicePixelRatio will change when you zoom the browser window.  This should allow you to test without needing a high DPI display.  When I make this modification zooming to 500% in the browser generates perfect text, with no blur at all.

2) The current code in RenderContext.ts renders incorrectly when not at 1:1 pixel ratio.  If you add this line to the end of RenderContext.resize, then rendering is kind of correct:
```javascript
this.raw.scale(this.dpiRatio, this.dpiRatio);
```
However, this causes mouse input to be offset by the scaling ratio.  I think the mouse position computation needs to either take into account the ratio, or it needs to work in style coordinates instead of canvas coordinates.

I suspect that some accommodation for dpiRatio needs to be added to RenderContext.resetTransform, setTransform, apply, preapply, etc., but I don't know which of these needs to be modified, or how.

**Comment by asthomas** [comment]
As of minerva 0.4.22 the RenderContext.ts code will not render correctly with a non 1:1 pixel ratio. It renders only a portion of the canvas and leaves the rest of the browser window black.  Forcing dpiRatio to 1 will fix this temporarily until a better implementation is available.

**Comment by BSick7** [comment]
This should be resolved with improvements to handle browser scaling and dpi.
